// ============================================================================
// MODULE: switch_led
// DESCRIPTION: Toggles LED outputs when a switch is pressed, with debouncing
// ============================================================================

/*
 * SYSTEM CLOCK (sys_clk) - CONCEPT
 * --------------------------------
 * The system clock is a periodic digital signal generated by an external
 * oscillator (typically a crystal) on the FPGA board. It serves as the
 * timing reference that synchronizes all sequential logic operations.
 * 
 * Characteristics of a 50 MHz system clock:
 *   - Frequency: 50,000,000 cycles per second
 *   - Period: 1/50,000,000 = 20 nanoseconds per cycle
 *   - The always @(posedge sys_clk) block executes once every 20ns
 * 
 * Visual representation of clock signal:
 *    ____      ____      ____      ____
 *   |    |____|    |____|    |____|    |____
 *   ^    ^    ^    ^
 *   |    |    |    |
 *  posedge posedge posedge posedge ... (trigger points)
 */

module switch_led (
    input sys_clk,          // System clock input from board oscillator
    input switch_pin,       // Switch input (typically active-low)
    output reg [5:0] led    // 6-bit LED output register
);

    // =========================================================================
    // REGISTER DECLARATIONS
    // =========================================================================
    
    reg switch_prev;        // Stores the switch state from previous cycle
                            // Used to detect state transitions (edges)
    
    reg [19:0] debounce_cnt; // 20-bit debounce counter
                             // Range: 0 to 2^20 - 1 = 0 to 1,048,575
                             // [19:0] means bits 19 (MSB) down to 0 (LSB)

    // =========================================================================
    // INITIALIZATION
    // =========================================================================
    
    initial begin
        led = 6'b000000;        // Initialize all 6 LEDs to OFF (binary 000000)
        switch_prev = 1'b1;     // Initialize to 1 (switch not pressed)
                                // Assumes active-low switch (1=open, 0=pressed)
        debounce_cnt = 20'd0;   // Initialize counter to decimal 0
    end

    // =========================================================================
    // DEBOUNCE COUNTER DESIGN
    // =========================================================================
    /*
     * WHY DEBOUNCING IS NEEDED:
     * Mechanical switches do not make clean electrical contact when pressed.
     * They "bounce" - rapidly open and close for several milliseconds before
     * settling. Without debouncing, each button press might register as
     * multiple presses.
     *
     * TIMING CALCULATION:
     * -------------------
     * Target debounce delay: approximately 5.4 milliseconds (ms)
     * System clock frequency: 50 MHz
     * Clock period: 1 / 50,000,000 Hz = 20 nanoseconds (ns)
     *
     * To achieve 5.4ms delay:
     *   Number of clock cycles = Total time / Clock period
     *                          = 0.0054 seconds / 0.00000002 seconds
     *                          = 270,000 cycles
     *
     * In the code below, the counter compares against 270,000.
     * When the counter reaches this value, approximately 5.4ms have elapsed.
     *
     * WHY 20 BITS?
     * ------------
     * Required count: 270,000
     * Binary representation requires enough bits to hold 270,000:
     *   2^18 = 262,144 (insufficient)
     *   2^19 = 524,288 (sufficient)
     *   2^20 = 1,048,576 (used - provides margin)
     * A 20-bit counter ([19:0]) can count up to 1,048,575.
     */

    always @(posedge sys_clk) begin
        // Debounce timer: count up to 270,000 clock cycles (~5.4ms at 50MHz)
        if (debounce_cnt < 20'd270000) begin
            // Counter has not reached target - keep counting
            debounce_cnt <= debounce_cnt + 1'b1;
        end else begin
            // Counter reached 270,000 (~5.4ms elapsed)
            debounce_cnt <= 20'd0;      // Reset counter for next debounce period
            switch_prev <= switch_pin;  // Capture current switch state

            // =================================================================
            // EDGE DETECTION LOGIC
            // =================================================================
            /*
             * FALLING EDGE DETECTION:
             * -----------------------
             * A falling edge occurs when a signal transitions from HIGH (1)
             * to LOW (0). For an active-low switch, this happens when the
             * button is pressed.
             *
             * Detection condition: (switch_prev == 1) AND (switch_pin == 0)
             * 
             * In Verilog: if (switch_prev && !switch_pin)
             *   - &&  : Logical AND operator (both conditions must be true)
             *   - !   : Logical NOT operator (inverts the value)
             *
             * State transition table for edge detection:
             * 
             * | Previous | Current | !Current | AND Result | Event          |
             * |----------|---------|----------|------------|----------------|
             * |    1     |    1    |    0     |     0      | No change (high)|
             * |    1     |    0    |    1     |     1      | FALLING EDGE   |
             * |    0     |    1    |    0     |     0      | Rising edge    |
             * |    0     |    0    |    1     |     0      | No change (low) |
             *
             * The falling edge (row 2) is the only case where the condition
             * evaluates to true, triggering the LED toggle.
             */

            if (switch_prev && !switch_pin) begin
                // Falling edge detected - switch was just pressed
                
                // LED TOGGLE OPERATION:
                // The ~ operator is bitwise NOT (inversion)
                // Each bit in 'led' is flipped: 0 becomes 1, 1 becomes 0
                //
                // Example:
                //   Before: led = 6'b001011 (binary) = 11 (decimal)
                //   After:  led = 6'b110100 (binary) = 52 (decimal)
                //
                // This creates a toggle effect each time the switch is pressed
                led <= ~led;
            end
        end
    end

endmodule
